### ISSUE TITLE
Feature Request. Add go standard module.

### ISSUE THREAD

**Issue by CaptainGopher** [r3inbowari/go-mod-explorer#18]
可以把go 标准库也加到module列表里吗？ 最好是放在列表的第一项。

**Comment by r3inbowari** [comment]
好滴

**Comment by r3inbowari** [comment]
v0.2.0 has been released, please try it. Thank you.

**Comment by CaptainGopher** [comment]
Something went wrong. Please check it .

<img width="455" alt="image" src="https://user-images.githubusercontent.com/28745416/168090603-ee57c6eb-7944-4160-9f56-715201e502d1.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/28745416/168090659-6478750a-7a84-4e4a-b6d3-2cb219f63f03.png">

**Comment by r3inbowari** [comment]
Is go.root configured in settings.json?

**Comment by CaptainGopher** [comment]
Neither `go.goroot` configuration in setting.json or environment variable `GOROOT` work.

**Comment by r3inbowari** [comment]
v0.2.1 may fix this, try it

**Comment by CaptainGopher** [comment]
There is another error occurred.

`ENOENT: no such file or directory, scandir '/"/users/yifei/go-sdk/go1.17"/src'`


<img width="2414" alt="image" src="https://user-images.githubusercontent.com/28745416/168101384-cafadc79-7261-4650-be14-5b3b50da180c.png">

**Comment by r3inbowari** [comment]
could you run `go env`, and give me the console printing, i don't have macos...

**Comment by CaptainGopher** [comment]
Excellent job, thank you very much! By the way, I mentioned this plugin [here](https://github.com/golang/vscode-go/issues/2236).
