### ISSUE TITLE
go command not found

### ISSUE THREAD

**Issue by CaptainGopher** [r3inbowari/go-mod-explorer#26]
The go command not found error occurred again in the latest version v0.2.6. See the snapshot below:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/28745416/169655192-f43354b4-e616-4910-9406-90223ca06d6d.png">

**Comment by CaptainGopher** [comment]
I'm pretty sure that I already configured go properly.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/28745416/169655395-f7ad4495-e9b2-41da-a414-4cecc8f924c5.png">

**Comment by r3inbowari** [comment]
this problem doesn't seems to be caused by 0.2.6. you can checkout to 0.2.4 and try again

**Comment by CaptainGopher** [comment]
Sorry, I think  it's because I opened VSCode in a wrong way. There is no problem with this plugin.
