### ISSUE TITLE
Bug: not working on windows 11

### ISSUE THREAD

**Issue by windzhu0514** [r3inbowari/go-mod-explorer#44]
only go stand library, not show project dependent library
![image](https://user-images.githubusercontent.com/5474294/206172309-11511c3d-5617-47b7-b888-a8ce03bd882a.png)

**Comment by r3inbowari** [comment]
Hi! @windzhu0514 Could you provide the go.mod and go.sum files for reproduction, thank you! And It should be noted that if there are some errors in the go.mod file, the libraries will not be updated correctly. So you can run `go list -mod=readonly -m -json -e all` in your workspace to see whether the list is fetched correctly.

**Comment by windzhu0514** [comment]
go.mod
```
module test

go 1.18

require github.com/google/uuid v1.3.0
```
go.sum
```
github.com/google/uuid v1.3.0 h1:t6JiXgmwXMjEs8VusXIJk2BXHsn+wx8BZdTaoZ5fu7I=
github.com/google/uuid v1.3.0/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
```
go list
```
$ go list -mod=readonly -m -json -e all
{
        "Path": "test",
        "Main": true,
        "Dir": "D:\\WorkspaceGo\\test",
        "GoMod": "D:\\WorkspaceGo\\test\\go.mod",
        "GoVersion": "1.18"
}
{
        "Path": "github.com/google/uuid",
        "Version": "v1.3.0",
        "Time": "2021-07-12T22:33:52Z",
        "Dir": "C:\\Users\\LJC\\go\\pkg\\mod\\github.com\\google\\uuid@v1.3.0",
        "GoMod": "C:\\Users\\LJC\\go\\pkg\\mod\\cache\\download\\github.com\\google\\uuid\\@v\\v1.3.0.mod"
}
```

also only show go stand library

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎7/‎29 ‎周五
操作系统版本	22623.1028
体验	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by r3inbowari** [comment]
Thanks , I wonder if there is an exception in the vscode console logs?
![image](https://user-images.githubusercontent.com/30739857/206361855-4af7305f-4b98-47f4-9a98-db1fa0405d53.png)

**Comment by windzhu0514** [comment]
![image](https://user-images.githubusercontent.com/5474294/206367722-cc454b9a-0518-4f66-8489-b2f182a5fd3e.png)
but there is alreadly has a go.mod file

**Comment by r3inbowari** [comment]
OKAY. @windzhu0514 I pushed a [patch](https://github.com/r3inbowari/go-mod-explorer/pull/43/commits/d63cde01d94db2146d7ce84b6229767a18af4064) with tag v0.3.7, pleace try it, emmm...maybe useful...

**Comment by windzhu0514** [comment]
it works,thanks a lot

![image](https://user-images.githubusercontent.com/5474294/206408419-a2c924c7-b645-4c12-924f-ffe75bf81979.png)
