### ISSUE TITLE
An error occurred when click 'Go SDK' folder.

### ISSUE THREAD

**Issue by jiangfangxin** [r3inbowari/go-mod-explorer#47]
My vscode is installed on windows computer (with Windows 11 system). My development enviroment is an ubuntu virtual machine. I installed go and vscode-server on that ubuntu virtual machine. Everything works well until this afternoon, I got an error notification below when I click 'Go SDK' folder in 'GOMOD EXPLORER' view:

![image](https://user-images.githubusercontent.com/10069506/210557220-ec0e98fa-0339-495f-a982-31f684b82d43.png)

Enviroment:
- vscode installed on Windows 11
- ubuntu virtual machine with go 1.19.3
- plugin installed on ubuntu Go Mod Explorer v0.3.8

Hope to get your help.

**Comment by r3inbowari** [comment]
Hi, @jiangfangxin I'm sorry, it's my fault.  Reverted to 0.3.7 now.
Hi, @zollum Do you have any way to fix it? It doesn't seem to work on other OS.

Related #45

**Comment by jiangfangxin** [comment]
Thanks! It works after changing the version to 0.3.7. 👍

**Comment by zollum** [comment]
really sorry, please check the new PR #49

**Comment by r3inbowari** [comment]
@zollum thank you very much!
