### ISSUE TITLE
Feature request: package filter searchbox

### ISSUE THREAD

**Issue by Tarick** [r3inbowari/go-mod-explorer#5]
When using multiple packages it becomes harder to find the needed package in the list. Having some simple filter box with fuzzy searching would be great.

**Comment by r3inbowari** [comment]
And If you want to use the filter, you can press the button in the blue box.
![image](https://user-images.githubusercontent.com/30739857/156578277-e9a87cf6-c4e6-4b79-9a1d-d8cc1a48a49e.png)

**Comment by r3inbowari** [comment]
![image](https://user-images.githubusercontent.com/30739857/156598833-c3c6b710-0866-4d38-92c9-33c3880585cf.png)
You can press the vertical scroll bar here to enter focus mode.
And then you can enter your keywords directly.

**Comment by Tarick** [comment]
Up to you :).
Still can't do that even when pressing that sidebar, probably there is some conflicting option on my side.

**Comment by r3inbowari** [comment]
The focused feature is done, you can enter `ctrl+shift+'` or press the search button to focus gomod.
 
![image](https://user-images.githubusercontent.com/30739857/156801819-3d8d8331-cfb0-448d-95fb-367bca593a71.png)

**Comment by Tarick** [comment]
First, this looking glass icon is now in File Editor too and clicking on it switches to gomod-explorer. I think this should be removed.

![image](https://user-images.githubusercontent.com/3610037/156831222-bba9cd72-fcca-40ea-8443-8a269306c21e.png)

Second, in go-mod-explorer clicking it doesn't make possible to search either, but I've started a fresh instance of VSCode and confirmed that this is my environment problem, fresh instance works correctly. I'm going to look up what's up with my setup.

**Comment by r3inbowari** [comment]
1. yea, i forgot to add a restriction for other explorer, try the new version.
2. maybe, I try it on linux, it works.
