### ISSUE TITLE
VS Code editor hangs and extension host has to restart

### ISSUE THREAD

**Issue by bitforce** [r3inbowari/go-mod-explorer#50]
**Current specs**
---
Macbook Pro 16-inch, 2021
Apple M1 Max
64GB
macOS Ventural 13.1

---
VS Code
Version: 1.76.2 (Universal)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No

**Issue**
<img width="1714" alt="Screenshot 2023-03-27 at 11 21 24 AM" src="https://user-images.githubusercontent.com/24510536/227991913-9c5c3dc7-7e90-43b2-876a-9551bff4c2de.png">

I'll get this error on startup and VS Code will randomly hang until the extension host terminates and auto-restarts. 

<img width="1610" alt="Screenshot 2023-03-27 at 11 43 18 AM" src="https://user-images.githubusercontent.com/24510536/227992755-250fa6e9-16a5-42a0-88da-b7f15b1a7762.png">

When switching tabs (using the Vim plugin), this behavior happens the most frequently.

**Comment by r3inbowari** [comment]
Hi,@bitfore. Thanks for your feedback. Could you provide the go version and the go.mod file?

**Comment by bitforce** [comment]
Unfortunately; I cannot, but I can describe the usage. Our codebase is comprised of many go.mod files: one at the root of the directory and a go.mod many of our subdirectories. Example:

PROJECT
  docker-compose.yml
  go.mod
  go.sum
  Makefile

**Comment by r3inbowari** [comment]
Okay, 'go env' can't provide it either, right? we need to know the version of go at least. Because this problem is roughly caused by the failure of parsing json. or will this error have any substantial impact, for example, a module is missing in go mod explorer, or there is no display at all.

> I'll get this error on startup and VS Code will randomly hang until the extension host terminates and auto-restarts.
I'll keep looking into this issue.

**Comment by bitforce** [comment]
Makes sense: `go version go1.19.4 darwin/arm64`

**Comment by r3inbowari** [comment]
Hi, @bitforce! Sorry for the late reply... We use a new way to parse the modules json, but I still suggest you to open devtool and report this error(you can desensitize relevant data, we only want to check the specific location of the error in the json).

error messages like this: 
![image](https://user-images.githubusercontent.com/30739857/232505024-d1b2592d-7289-4874-ab24-e2959261dbf5.png)
