### ISSUE TITLE
The installation is successful and cannot be used

### ISSUE THREAD

**Issue by ForeverCm** [r3inbowari/go-mod-explorer#51]
![201ca0397f15d83d25f4ba54b1a61fc0](https://user-images.githubusercontent.com/18618391/228144022-513fd0ed-3067-4cae-b3c7-ddd1e10a084d.png)

install go mod explorer success，but not show on left vscode

![image](https://user-images.githubusercontent.com/18618391/228144220-7a72a407-7872-42e5-b56e-f06e696d568e.png)

**Comment by r3inbowari** [comment]
Hi, @ForeverCm, Is `vscode-go` installed?

**Comment by ForeverCm** [comment]
yes, my vscode can run go code success，but can‘t used Go Mod Explore 

i understand，if Go Mod Explore can use，It should look like this，it should has GOMOD EXPLORE folder on the workspace

![image](https://user-images.githubusercontent.com/18618391/229405605-d859b92e-01c8-426f-840a-f4a637269df1.png)

**Comment by r3inbowari** [comment]
Please provide your vscode-go version information and confirm that whether the go mod explorer is hidden in the right sidebar. The right sidebar is not visible when there is only one treeview.

It is best to provide some devtools console logs.

Thank you!

**Comment by r3inbowari** [comment]
on the right sidebar, if we click hide, the go mod explorer will not visible:
![image](https://user-images.githubusercontent.com/30739857/229537589-b4235518-d6f4-4a1b-9439-caba588a496b.png)


or 
![image](https://user-images.githubusercontent.com/30739857/229537246-b7cbd2de-8805-45ca-8663-a8fb0cbcc2da.png)

**Comment by r3inbowari** [comment]
![image](https://user-images.githubusercontent.com/30739857/229539551-99a0a245-dd54-4761-8e68-70a6f23a12fc.png)
I noticed that the ext loads normally, unless you see an error message in the bottom right corner.

**Comment by ForeverCm** [comment]
![image](https://user-images.githubusercontent.com/18618391/229665305-c9a3a55e-ece0-42c5-9a69-3183cf977c1d.png)

above is my vscode version




![image](https://user-images.githubusercontent.com/18618391/229665742-346e61ce-7a34-4209-8203-2723197a3029.png)
If I check the right box here, an error is reported in the bottom right corner，Does it have anything to do with this?

**Comment by ForeverCm** [comment]
![image](https://user-images.githubusercontent.com/18618391/229668095-e2b6a5b1-e4f4-42f4-9d5d-75ca8230a669.png)

**Comment by ForeverCm** [comment]
![image](https://user-images.githubusercontent.com/18618391/229669891-e7f70298-f2a8-4461-89c1-269d90dd0ed2.png)

**Comment by r3inbowari** [comment]
> Is this what you mean by vscode-go?

Yes

**Comment by r3inbowari** [comment]
> ![image](https://user-images.githubusercontent.com/18618391/229665305-c9a3a55e-ece0-42c5-9a69-3183cf977c1d.png)
> 
> 
> 
> above is my vscode version
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/18618391/229665742-346e61ce-7a34-4209-8203-2723197a3029.png)
> 
> If I check the right box here, an error is reported in the bottom right corner，Does it have anything to do with this?

Your vscod-go doesn't seem to start properly, either. Did you hide it?

**Comment by ForeverCm** [comment]
> > ![image](https://user-images.githubusercontent.com/18618391/229665305-c9a3a55e-ece0-42c5-9a69-3183cf977c1d.png)
> > above is my vscode version
> > ![image](https://user-images.githubusercontent.com/18618391/229665742-346e61ce-7a34-4209-8203-2723197a3029.png)
> > If I check the right box here, an error is reported in the bottom right corner，Does it have anything to do with this?
> 
> Your vscod-go doesn't seem to start properly, either. Did you hide it?

My vscode running go program is ok, how to determine and check if my vscode-go is start correctly

**Comment by r3inbowari** [comment]
![image](https://user-images.githubusercontent.com/30739857/229693330-c228a1da-2345-417b-a64b-ff6d0beab294.png)
When vscode is running, there will be a version indication below.

**Comment by ForeverCm** [comment]
> ![image](https://user-images.githubusercontent.com/30739857/229693330-c228a1da-2345-417b-a64b-ff6d0beab294.png) When vscode is running, there will be a version indication below.

![image](https://user-images.githubusercontent.com/18618391/229707240-6546b4da-c727-48b2-87fc-0ead9fb4d684.png)
I don't have it here, but the program works fine

**Comment by r3inbowari** [comment]
We have comfirmed that both the vscode-go and go mod explorer exts are not working on your computer.

**Comment by r3inbowari** [comment]
I think you should confirm why vscode-go is not running at first.

**Comment by ForeverCm** [comment]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/18618391/229962693-67aeb5a4-25bb-4bd7-922a-0ec0fcc5921f.png">

**Comment by r3inbowari** [comment]
Do you know vscode-go?

**Comment by r3inbowari** [comment]
Your vscode-go is not working properly. It is a prerequisite for running go mod explorer.

**Comment by r3inbowari** [comment]
Go binary and vscode-go are two different things. right, please don't confuse them.

**Comment by ForeverCm** [comment]
> Do you know vscode-go?

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/18618391/229971269-27164bc1-8634-47ef-a518-b1897a0fde16.png">
is this ?

**Comment by r3inbowari** [comment]
> > Is this what you mean by vscode-go?
> 
> Yes

Duplicate ACK.

**Comment by ForeverCm** [comment]
> > > Is this what you mean by vscode-go?
> > 
> > 
> > Yes
> 
> Duplicate ACK.

I see that my vscode-go is already installed

**Comment by r3inbowari** [comment]
The problem is that he is not running properly...😄

> > > > Is this what you mean by vscode-go?
> > > 
> > > 
> > > Yes
> > 
> > 
> > Duplicate ACK.
> 
> I see that my vscode-go is already installed

**Comment by ForeverCm** [comment]
But why is there not running properly？

**Comment by r3inbowari** [comment]
![image](https://user-images.githubusercontent.com/30739857/229972046-cc4e0453-bfbe-491c-a02e-88b619e172e4.png)

**Comment by r3inbowari** [comment]
I'm not sure... Can you provide your work directory structure?

**Comment by ForeverCm** [comment]
I tried uninstalling the vscode software and the vscode-go extension, but neither worked

> ![image](https://user-images.githubusercontent.com/30739857/229972046-cc4e0453-bfbe-491c-a02e-88b619e172e4.png)

yes，i see

**Comment by ForeverCm** [comment]
I tried uninstalling the vscode software and the vscode-go extension, but neither worked

**Comment by r3inbowari** [comment]
> Your vscode-go is not working properly. It is a prerequisite for running go mod explorer.



> I tried uninstalling the vscode software and the vscode-go extension, but neither worked
> 
> > ![image](https://user-images.githubusercontent.com/30739857/229972046-cc4e0453-bfbe-491c-a02e-88b619e172e4.png)
> 
> yes，i see

So you must ensure that your vscode-go can run.

**Comment by ForeverCm** [comment]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/18618391/229972481-816dc53d-dd9f-4194-b7af-14e2dd831416.png">

my vscode-go not running properly，I found that my go install doesn't even work，

**Comment by r3inbowari** [comment]
> my vscode-go not running properly，I found that my go install doesn't even work，

I think this is caused by your network problem. such as 404 not found.

**Comment by r3inbowari** [comment]
`go.tools.install` belongs to the command category of vscode-go. But your vscode-go was not work.

**Comment by r3inbowari** [comment]
Even your go language services are not working.

**Comment by ForeverCm** [comment]
> `go.tools.install` belongs to the command category of vscode-go. But your vscode-go was not work.

yes，I see，I'll try to solve the vscode-go problem first

**Comment by r3inbowari** [comment]
Because they were not installed at all, let alone running.

> Even your go language services are not working.

**Comment by ForeverCm** [comment]
> Because they were not installed at all, let alone running.
> 
> > Even your go language services are not working.

What does this mean?

**Comment by r3inbowari** [comment]
![image](https://user-images.githubusercontent.com/30739857/229973526-01a92754-303c-431b-ae0c-0f096b0defe2.png)

You'd better provide your log info.

**Comment by r3inbowari** [comment]
> > Because they were not installed at all, let alone running.
> > > Even your go language services are not working.
> 
> What does this mean?

![image](https://user-images.githubusercontent.com/30739857/229973683-c4a55146-0719-4194-959a-1afbc60701a3.png)

**Comment by ForeverCm** [comment]
> ![image](https://user-images.githubusercontent.com/30739857/229973526-01a92754-303c-431b-ae0c-0f096b0defe2.png)
> 
> You'd better provide your log info.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/18618391/229974294-a6f8207e-c83f-43dd-9856-f9f280004be3.png">

**Comment by ForeverCm** [comment]
> <img alt="image" width="1036" src="https://user-images.githubusercontent.com/18618391/229972481-816dc53d-dd9f-4194-b7af-14e2dd831416.png">
> 
> my vscode-go not running properly，I found that my go install doesn't even work，

https://github.com/microsoft/vscode-go/issues/755    I checked my goroot, gopath, version look good, and also can execute go run run program also, so I do not know where the problem is

**Comment by r3inbowari** [comment]
> > <img alt="image" width="1036" src="https://user-images.githubusercontent.com/18618391/229972481-816dc53d-dd9f-4194-b7af-14e2dd831416.png">
> > my vscode-go not running properly，I found that my go install doesn't even work，
> 
> [microsoft/vscode-go#755](https://github.com/microsoft/vscode-go/issues/755) I checked my goroot, gopath, version look good, and also can execute go run run program also, so I do not know where the problem is

https://github.com/microsoft/vscode-go/issues/755#issuecomment-340183462
Have you tried it?

**Comment by r3inbowari** [comment]
Have you ever checked your network? Maybe you should `ping google.com` to check it.

**Comment by ForeverCm** [comment]
> > > <img alt="image" width="1036" src="https://user-images.githubusercontent.com/18618391/229972481-816dc53d-dd9f-4194-b7af-14e2dd831416.png">
> > > my vscode-go not running properly，I found that my go install doesn't even work，
> > 
> > 
> > [microsoft/vscode-go#755](https://github.com/microsoft/vscode-go/issues/755) I checked my goroot, gopath, version look good, and also can execute go run run program also, so I do not know where the problem is
> 
> [microsoft/vscode-go#755 (comment)](https://github.com/microsoft/vscode-go/issues/755#issuecomment-340183462) Have you tried it?

I tried, but not yet solved, I'll try other methods, thank you for your answer, and I'll reply here after I solve it

**Comment by ForeverCm** [comment]
![image](https://user-images.githubusercontent.com/18618391/230267707-18f857c3-5365-411d-99a6-6de7bcef236d.png)
I solved the problem，ow my go and gomodexplore are ok

**Comment by ForeverCm** [comment]
> ![image](https://user-images.githubusercontent.com/18618391/230267707-18f857c3-5365-411d-99a6-6de7bcef236d.png) I solved the problem，ow my go and gomodexplore are ok

![588768b982344fcfd7262080a58388da](https://user-images.githubusercontent.com/18618391/230267858-8f939519-05b8-4071-bbf9-4ff17e725428.png)
chatgpt helped me solve this problem because the vscode extensions were reporting errors, directly removing the $HOME/.vscode/extensions folder and reinstalling the extensions solved it

**Comment by ForeverCm** [comment]
Thank you very much for your answer. We can end this question

**Comment by ForeverCm** [comment]
chatgpt is great, really a good helper

**Comment by r3inbowari** [comment]
OK.
