### ISSUE TITLE
Add to https://open-vsx.org/

### ISSUE THREAD

**Issue by smerschjohann** [r3inbowari/go-mod-explorer#53]
Hi! Thanks for this very useful extension!

As I'm also using code-server a lot which does not have the VSCode Marketplace, it would be nice to have your extension directly in the Open-Source registry as well. Right now I have to download it as file from the Marketplace and manually install the extension.

Could you publish your extension to the https://open-vsx.org/ registry? 
That would allow Opensource VSCode variants to catch your extension.

**Comment by r3inbowari** [comment]
Hi, @smerschjohann, thanks for your proposal. Here is the open-vsx registry link: [Go Mod Explorer](https://open-vsx.org/extension/r3inbowari/gomodexplorer)

**Comment by smerschjohann** [comment]
thank you! But it seems that you did not claim that page so far. It shows up as unverified. Otherwise it works already :)

**Comment by r3inbowari** [comment]
Yes, We need to wait for approval.

**Comment by r3inbowari** [comment]
Claim completed! https://github.com/EclipseFdn/open-vsx.org/issues/1806
