### ISSUE TITLE
function navigation slow

### ISSUE THREAD

**Issue by SupNewBeen** [r3inbowari/go-mod-explorer#60]
Type: <b>Bug</b>

It is easy to replicate; if you open a large Golang project, you will notice that the navigation between functions is very slow.

Extension version: 0.3.11
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin x64 22.5.0
Modes:
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0056
Connection to 'ssh-remote+7b22686f73744e616d65223a22446576636c6f75645f706572736f6e616c227d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.35GB free)|
|Process Argv|--crash-reporter-id 19480d25-2471-4e57-8c41-4d5e0c43bf4b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Devcloud_personal|
|OS|Linux x64 3.10.107-1-tlinux2_kvm_guest-0056|
|CPUs|Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz (16 x 2494)|
|Memory (System)|31.10GB (23.88GB free)|
|VM|0%|

Connection to 'ssh-remote+7b22686f73744e616d65223a22446576636c6f75645f706572736f6e616c227d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by r3inbowari** [comment]
Hi, @SupNewBeen, Thank you for your report. It needs to be clear that the function navigation is performed by the extension `vscode-go`. `go-mod-explorer` only use the navigation result(path) to reveal the code file position. 

So you need to clearly state the following two diff situations:
1. the `navigate to code` process is slow.
2. the `navigate to code` is completed quickly, but `go-mod-explorer` is very slow to reveal.
