### ISSUE TITLE
Vim jump, mouse focus problem

### ISSUE THREAD

**Issue by KingPuiWong** [r3inbowari/go-mod-explorer#68]
Using the vim plugin, press ctrl +] to the dependent code after the mouse focus jumps to the Go Mod Explorer activity bar, causing me to move the mouse to click on the line of code before I can continue to use vim

**Comment by r3inbowari** [comment]
Maybe it helps you? https://github.com/r3inbowari/go-mod-explorer/issues/61#issuecomment-1735981916

**Comment by KingPuiWong** [comment]
> Maybe it helps you? [#61 (comment)](https://github.com/r3inbowari/go-mod-explorer/issues/61#issuecomment-1735981916)

Yes,thanks!
